__author__="stkerr"
__date__ ="$Jan 14, 2011 10:49:15 AM$"

# Import the tools
from css_properties import *
from node import *
from render_engine import *

# Base set of tag imports
from tags.tag_basefont import *
from tags.tag_colgroup import *
from tags.tag_frame import *
from tags.tag_iframe import *
from tags.tag_noframes import *
from tags.tag_select import *
from tags.tag_th import *
from tags.tag_bdo import *
from tags.tag_dd import *
from tags.tag_frameset import *
from tags.tag_img import *
from tags.tag_noscript import *
from tags.tag_small import *
from tags.tag_thead import *
from tags.tag_big import *
from tags.tag_del import *
from tags.tag_h1 import *
from tags.tag_input import *
from tags.tag_object import *
from tags.tag_span import *
from tags.tag_title import *
from tags.tag_blockquote import *
from tags.tag_dfn import *
from tags.tag_h2 import *
from tags.tag_ins import *
from tags.tag_ol import *
from tags.tag_strike import *
from tags.tag_tr import *
from tags.tag_body import *
from tags.tag_dir import *
from tags.tag_h3 import *
from tags.tag_isindex import *
from tags.tag_optgroup import *
from tags.tag_strong import *
from tags.tag_tt import *
from tags.tag_a import *
from tags.tag_body import *
from tags.tag_div import *
from tags.tag_h4 import *
from tags.tag_kbd import *
from tags.tag_option import *
from tags.tag_style import *
from tags.tag_u import *
from tags.tag_abbr import *
from tags.tag_br import *
from tags.tag_dl import *
from tags.tag_h5 import *
from tags.tag_label import *
from tags.tag_p import *
from tags.tag_sub import *
from tags.tag_ul import *
from tags.tag_acronym import *
from tags.tag_button import *
#from tags.tag_doctype import *
from tags.tag_h6 import *
from tags.tag_legend import *
from tags.tag_param import *
from tags.tag_sup import *
from tags.tag_var import *
from tags.tag_address import *
from tags.tag_caption import *
from tags.tag_dt import *
from tags.tag_head import *
from tags.tag_li import *
from tags.tag_pre import *
from tags.tag_table import *
from tags.tag_applet import *
from tags.tag_center import *
from tags.tag_em import *
from tags.tag_hr import *
from tags.tag_link import *
from tags.tag_q import *
from tags.tag_tbody import *
from tags.tag_area import *
from tags.tag_cite import *
from tags.tag_fieldset import *
from tags.tag_html import *
from tags.tag_map import *
from tags.tag_s import *
from tags.tag_td import *
from tags.tag_b import *
from tags.tag_code import *
from tags.tag_font import *
from tags.tag_html import *
from tags.tag_menu import *
from tags.tag_samp import *
from tags.tag_textarea import *
from tags.tag_base import *
from tags.tag_col import *
from tags.tag_form import *
from tags.tag_i import *
from tags.tag_meta import *
from tags.tag_script import *
from tags.tag_tfoot import *

# HTML 5 imports
from tags.html5.tag_article import *
from tags.html5.tag_aside import *
from tags.html5.tag_audio import *
from tags.html5.tag_canvas import *
from tags.html5.tag_command import *
from tags.html5.tag_datalist import *
from tags.html5.tag_details import *
from tags.html5.tag_embed import *
from tags.html5.tag_eventsource import *
from tags.html5.tag_figcaption import *
from tags.html5.tag_figure import *
from tags.html5.tag_footer import *
from tags.html5.tag_header import *
from tags.html5.tag_hgroup import *
from tags.html5.tag_keygen import *
from tags.html5.tag_mark import *
from tags.html5.tag_menu import *
from tags.html5.tag_meter import *
from tags.html5.tag_nav import *
from tags.html5.tag_output import *
from tags.html5.tag_progress import *
from tags.html5.tag_section import *
from tags.html5.tag_source import *
from tags.html5.tag_summary import *
from tags.html5.tag_time import *
from tags.html5.tag_video import *