"""
Gen.py
This is just a helper file that will generate the python
tag files quickly, so they don't have to be done by hand
each time.
"""

def printfile(name, filename, required_attributes):
	output =  """
import WebSpinner.tags

class Tag_"""
	output += name.title() 
	output += """(WebSpinner.Node):
	tag_string = \""""
	output += name 
	output += "\""
	output += "\n"
	output += "\trequired_attributes = " + str(required_attributes)
	output += "\n"

	f = open(filename + ".py", "w+")
	f.write(output)
	f.close()


#printfile("!doctype", "tag_doctype", [])
printfile("a", 				"tag_a", 				[])
printfile("abbr", 			"tag_abbr", 			[])
printfile("acronym", 		"tag_acronym", 			[])
printfile("address", 		"tag_address", 			[])
printfile("applet", 		"tag_applet", 			["code","object"])
printfile("area", 			"tag_area", 			["alt"])
printfile("b", 				"tag_b", 				[])
printfile("base", 			"tag_base", 			[])
printfile("basefont", 		"tag_basefont", 		[])
printfile("bdo", 			"tag_bdo", 				["dir"])
printfile("big", 			"tag_big", 				[])
printfile("blockquote", 	"tag_blockquote", 		[])
printfile("body", 			"tag_body", 			[])
printfile("br", 			"tag_br", 				[])
printfile("button", 		"tag_button", 			[])
printfile("caption", 		"tag_caption", 			[])
printfile("center", 		"tag_center", 			[])
printfile("cite", 			"tag_cite", 			[])
printfile("code", 			"tag_code", 			[])
printfile("col", 			"tag_col", 				[])
printfile("colgroup", 		"tag_colgroup", 		[])
printfile("dd", 			"tag_dd", 				[])
printfile("del", 			"tag_del", 				[])
printfile("dfn", 			"tag_dfn", 				[])
printfile("dir", 			"tag_dir", 				[])
printfile("div", 			"tag_div", 				[])
printfile("dl", 			"tag_dl", 				[])
printfile("dt", 			"tag_dt", 				[])
printfile("em", 			"tag_em", 				[])
printfile("fieldset", 		"tag_fieldset", 		[])
printfile("font", 			"tag_font", 			[])
printfile("form", 			"tag_form", 			["action"])
printfile("frame", 			"tag_frame", 			[])
printfile("frameset", 		"tag_frameset", 		[])
printfile("h1", 			"tag_h1", 				[])
printfile("h2", 			"tag_h2", 				[])
printfile("h3", 			"tag_h3", 				[])
printfile("h4", 			"tag_h4", 				[])
printfile("h5", 			"tag_h5", 				[])
printfile("h6", 			"tag_h6", 				[])
printfile("head", 			"tag_head", 			[])
printfile("hr", 			"tag_hr", 				[])
printfile("html", 			"tag_html", 			["xmlns"])
printfile("i", 				"tag_i", 				[])
printfile("iframe", 		"tag_iframe", 			[])
printfile("img", 			"tag_img", 				["alt","src"])
printfile("input", 			"tag_input", 			[])
printfile("ins", 			"tag_ins", 				[])
printfile("isindex", 		"tag_isindex", 			[])
printfile("kbd", 			"tag_kbd", 				[])
printfile("label", 			"tag_label", 			[])
printfile("legend", 		"tag_legend", 			[])
printfile("li", 			"tag_li", 				[])
printfile("link", 			"tag_link", 			[])
printfile("map", 			"tag_map", 				["name"])
printfile("menu", 			"tag_menu", 			[])
printfile("meta", 			"tag_meta", 			["content"])
printfile("noframes", 		"tag_noframes", 		[])
printfile("noscript", 		"tag_noscript", 		[])
printfile("object", 		"tag_object", 			[])
printfile("ol", 			"tag_ol", 				[])
printfile("optgroup", 		"tag_optgroup", 		["label"])
printfile("option", 		"tag_option", 			[])
printfile("p", 				"tag_p", 				[])
printfile("param", 			"tag_param", 			["name"])
printfile("pre", 			"tag_pre", 				[])
printfile("q", 				"tag_q", 				[])
printfile("s", 				"tag_s", 				[])
printfile("samp", 			"tag_samp", 			[])
printfile("script", 		"tag_script", 			["type"])
printfile("select", 		"tag_select", 			[])
printfile("small", 			"tag_small", 			[])
printfile("span", 			"tag_span", 			[])
printfile("strike", 		"tag_strike", 			[])
printfile("strong", 		"tag_strong", 			[])
printfile("style", 			"tag_style", 			["type"])
printfile("sub", 			"tag_sub", 				[])
printfile("sup", 			"tag_sup", 				[])
printfile("table", 			"tag_table", 			[])
printfile("tbody", 			"tag_tbody", 			[])
printfile("td", 			"tag_td", 				[])
printfile("textarea", 		"tag_textarea", 		["cols", "rows"])
printfile("tfoot", 			"tag_tfoot", 			[])
printfile("th", 			"tag_th", 				[])
printfile("thead", 			"tag_thead", 			[])
printfile("title", 			"tag_title", 			[])
printfile("tr", 			"tag_tr", 				[])
printfile("tt", 			"tag_tt", 				[])
printfile("u", 				"tag_u", 				[])
printfile("ul", 			"tag_ul", 				[])
printfile("var", 			"tag_var", 				[])
printfile("article", 		"html5/tag_article",	[])
printfile("aside", 			"html5/tag_aside", 		[])
printfile("audio", 			"html5/tag_audio", 		[])
printfile("canvas", 		"html5/tag_canvas", 	[])
printfile("command", 		"html5/tag_command", 	[])
printfile("datalist", 		"html5/tag_datalist", 	[])
printfile("details", 		"html5/tag_details", 	[])
printfile("embed", 			"html5/tag_embed", 		[])
printfile("eventsource", 	"html5/tag_eventsource",[])
printfile("figcaption", 	"html5/tag_figcaption", [])
printfile("figure", 		"html5/tag_figure", 	[])
printfile("footer", 		"html5/tag_footer", 	[])
printfile("header", 		"html5/tag_header", 	[])
printfile("hgroup", 		"html5/tag_hgroup", 	[])
printfile("keygen", 		"html5/tag_keygen", 	[])
printfile("mark", 			"html5/tag_mark", 		[])
printfile("menu", 			"html5/tag_menu", 		[])
printfile("meter", 			"html5/tag_meter", 		[])
printfile("nav", 			"html5/tag_nav", 		[])
printfile("output", 		"html5/tag_output", 	[])
printfile("progress", 		"html5/tag_progress", 	[])
printfile("section", 		"html5/tag_section", 	[])
printfile("source", 		"html5/tag_source", 	[])
printfile("summary", 		"html5/tag_summary", 	[])
printfile("time", 			"html5/tag_time", 		[])
printfile("video", 			"html5/tag_video", 		[])
		